### ISSUE TITLE
Is this transformer comparable to babel-plugin-add-react-displayname?

### ISSUE THREAD

**Issue by tranvansang** [lud2k/ts-react-display-name#16]
Hello, thanks for the useful plugin.

I am considering migrating from babel-loader to ts-loader for simplicity and performance.
`babel-plugin-add-react-displayname` is currently blocking the migration. I am finding the alternative and found your transformer.

I haven't integrated your transformer yet. But I looked at your source code.
It looks like that `ts-react-display-name` requires and relies only on component type declaration (correct me if I am wrong) while babel-plugin-add-react-displayname doesn't.

Here is the source code of `babel-plugin-add-react-displayname`: https://github.com/opbeat/babel-plugin-add-react-displayname/blob/master/index.js

My question is in the title of this issue: Is `ts-react-display-name` comparable to `babel-plugin-add-react-displayname`?

**Comment by lud2k** [comment]
Hi!
Yes I believe it is similar to babel-plugin-add-react-displayname.
I created this because my previous company did not use babel. Didn't want to add babel just for this plugin.
I haven't touched this project in a while since I've moved to a new company which does not use React.

**Comment by tranvansang** [comment]
Thank you. Let me give it a try and I will back to the thread if there is any problem
